name: "docker build and push for ljc-cli"

on:
  push:
    tags:
      - "*"

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TARGETOS: linux
  TARGETARCH: amd64
  DEFAULT_DOCKERFILE_NAME: Dockerfile

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set ENV variables
        run: |
          echo "GITHUB_REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: |
          docker buildx build --platform=${TARGETOS}/${TARGETARCH} -f images/${GITHUB_REPO_NAME}/${DEFAULT_DOCKERFILE_NAME} \
            --build-arg TARGETOS=${TARGETOS} \
            --build-arg TARGETARCH=${TARGETARCH} \
            -t ${{ secrets.DOCKER_REPO_NAME }}:${{ github.ref_name }} .
          docker images

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_REPO_NAME }}:${{ github.ref_name }}
